config/routes.rb
Rails.application.routes.draw do

  get '/about', to: 'static_pages#about'
  get '/instructions', to: 'static_pages#instructions'
  get '/profile', to: 'users#home'

  devise_for :users, path: '', path_names: {
  sign_in: 'login',
  sign_out: 'logout',
  sign_up: 'register'
}

  resources :matches, except: [:edit, :new] do
    member do
      patch 'challenge', to: 'matches#challenge'
    end
  end

  resources :users
  root "matches#index"

  resources :chat_rooms, only: [:show]

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  # belongs_to :user
  belongs_to :match
  has_many :messages, dependent: :destroy
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/create.html.erb
<h1>ChatRooms#create</h1>
<p>Find me in app/views/chat_rooms/create.html.erb</p>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
            <h2><%= @chat_room.title %></h2>

            <div class="message-wr">
                <div id="messages" class="messages" data-chat-room-id="<%= @chat_room.id %>">
                    <div id="messages-table" class="messages-table">
                        <%= render @chat_room.messages %>
                    </div>
                </div>
            </div>

            <%= form_for @message, url: '#' do |f| %>
            <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
            <div class="form-group">
                <!-- <%= f.label :body %> -->
                <%= f.text_area :body, class: 'form-control' %>
                <small class="text-muted">From 2 to 1000 characters</small>
            </div>

            <!-- <%= f.submit "Post", class: 'btn btn-primary btn-lg' %> -->
            <% end %>