config/routes.rb
Rails.application.routes.draw do

  get '/about', to: 'static_pages#about'
  get '/instructions', to: 'static_pages#instructions'
  get '/profile', to: 'users#home'

  devise_for :users, path: '', path_names: {
  sign_in: 'login',
  sign_out: 'logout',
  sign_up: 'register'
}

  resources :matches, except: [:edit, :new] do
    member do
      patch 'challenge', to: 'matches#challenge'
    end
  end

  resources :users
  root "matches#index"

  resources :chat_rooms, only: [:show]

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  validates :gameboard, length: { is: 36 }

  has_one :chat_room

  belongs_to :playerx, :class_name => "User"
  belongs_to :playero, :class_name => "User", optional: true
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @availablematches = Match.where(playero_id:nil).first(12)

    @livematches = Match.where(outcome:'N').where.not(playero_id:nil).last(8)

    @match = Match.new
    @match.playerx_id = current_user.id
  end

  def show
    @match = Match.find(params[:id])
    @chat_room = @match.chat_room
    @user = current_user.id

    @message = Message.new

    respond_to do |format|
      format.html
      format.json  { render json: {
          match: @match,
          user: @user
        }}
    end
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      # Find match cos build needs database datatype
      match = Match.find(@match.id)
      @chat_room = match.build_chat_room()
      @chat_room.save
      redirect_to @match
    else
      render 'index'
    end
  end

  def challenge
    @match = Match.find(params[:id])

    if (@match.playero_id.blank? == true && @match.playerx_id != current_user.id)

      if @match.update_attributes(playero_id: current_user.id)
        ActionCable.server.broadcast "gameroom_channel_#{@match.id}",
          id: @match.id,
          gameboard:  @match.gameboard,
          moveindex: @match.moveindex,
          currentplayer: @match.currentplayer,
          playerx:  @match.playerx_id,
          playero: @match.playero_id,
          outcome: @match.outcome,
          winner: @match.winner,
          xtimebank: @match.xtimebank,
          otimebank: @match.otimebank,
          playeroname: @match.playero.name
      end
      redirect_to match_path
    end
  end

  def update
    @match = Match.find(params[:id])

    if @match.update(match_params)
      ActionCable.server.broadcast "gameroom_channel_#{@match.id}",
                                   id: @match.id,
                                   gameboard:  @match.gameboard,
                                   moveindex: @match.moveindex,
                                   currentplayer: @match.currentplayer,
                                   playerx:  @match.playerx_id,
                                   playero: @match.playero_id,
                                   outcome: @match.outcome,
                                   winner: @match.winner,
                                   playerid: current_user.id,
                                   xtimebank: @match.xtimebank,
                                   otimebank: @match.otimebank
      head :ok
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    redirect_to matches_path
  end

  private
  def match_params
    params.require(:match).permit(:gameboard, :moveindex, :currentplayer, :playerx_id, :playero_id, :outcome, :winner, :xtimebank, :otimebank)
  end

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_game_board.erb
<div class="game-board-container" data-game-room-id="<%= @match.id %>">

  <div class="top-btn-container">
    <div class="rotate-btn top-btn" id="rotate-right-0"></div>
    <div class="rotate-btn top-btn" id="rotate-left-1"></div>
  </div>

  <div class="left-btn-container">
    <div class="rotate-btn left-btn" id="rotate-left-0"></div>
    <div class="rotate-btn left-btn" id="rotate-right-2"></div>
  </div>

  <div class="game-board">
    <div class="game-tile" id="game-tile-0">
      <div class="game-square" data-row="0" data-col="0"></div>
      <div class="game-square" data-row="0" data-col="1"></div>
      <div class="game-square" data-row="0" data-col="2"></div>
      <div class="game-square" data-row="1" data-col="0"></div>
      <div class="game-square" data-row="1" data-col="1"></div>
      <div class="game-square" data-row="1" data-col="2"></div>
      <div class="game-square" data-row="2" data-col="0"></div>
      <div class="game-square" data-row="2" data-col="1"></div>
      <div class="game-square" data-row="2" data-col="2"></div>
    </div>
    <div class="game-tile" id="game-tile-1">
      <div class="game-square" data-row="0" data-col="3"></div>
      <div class="game-square" data-row="0" data-col="4"></div>
      <div class="game-square" data-row="0" data-col="5"></div>
      <div class="game-square" data-row="1" data-col="3"></div>
      <div class="game-square" data-row="1" data-col="4"></div>
      <div class="game-square" data-row="1" data-col="5"></div>
      <div class="game-square" data-row="2" data-col="3"></div>
      <div class="game-square" data-row="2" data-col="4"></div>
      <div class="game-square" data-row="2" data-col="5"></div>
    </div>
    <div class="game-tile" id="game-tile-2">
      <div class="game-square" data-row="3" data-col="0"></div>
      <div class="game-square" data-row="3" data-col="1"></div>
      <div class="game-square" data-row="3" data-col="2"></div>
      <div class="game-square" data-row="4" data-col="0"></div>
      <div class="game-square" data-row="4" data-col="1"></div>
      <div class="game-square" data-row="4" data-col="2"></div>
      <div class="game-square" data-row="5" data-col="0"></div>
      <div class="game-square" data-row="5" data-col="1"></div>
      <div class="game-square" data-row="5" data-col="2"></div>
    </div>
    <div class="game-tile" id="game-tile-3">
      <div class="game-square" data-row="3" data-col="3"></div>
      <div class="game-square" data-row="3" data-col="4"></div>
      <div class="game-square" data-row="3" data-col="5"></div>
      <div class="game-square" data-row="4" data-col="3"></div>
      <div class="game-square" data-row="4" data-col="4"></div>
      <div class="game-square" data-row="4" data-col="5"></div>
      <div class="game-square" data-row="5" data-col="3"></div>
      <div class="game-square" data-row="5" data-col="4"></div>
      <div class="game-square" data-row="5" data-col="5"></div>
    </div>
  </div>

  <div class="right-btn-container">
    <div class="rotate-btn right-btn" id="rotate-right-1"></div>
    <div class="rotate-btn right-btn" id="rotate-left-3"></div>
  </div>

  <div class="bottom-btn-container">
    <div class="rotate-btn bottom-btn" id="rotate-right-3"></div>
    <div class="rotate-btn bottom-btn" id="rotate-left-2"></div>
  </div>
</div>

app/views/matches/_hidden_create_form.erb
<%= form_for @match, html: {class: 'create-gameroom-form'} do |f| %>
    <%= f.hidden_field :gameboard %>
    <%= f.hidden_field :currentplayer %>
    <%= f.hidden_field :moveindex %>
    <%= f.hidden_field :playerx_id %>
    <%= f.hidden_field :outcome %>
    <%= f.submit "Create Game Room", class: "btn btn-default btn-success" %>
<% end %>

app/views/matches/_hidden_gameboard_form.erb
<%= form_for @match, html: {class: 'game-board-form'}, remote: true do |f| %>
    <%= f.hidden_field :gameboard %>
    <%= f.hidden_field :currentplayer %>
    <%= f.hidden_field :moveindex %>
    <%= f.hidden_field :playerx_id %>
    <%= f.hidden_field :playero_id %>
    <%= f.hidden_field :outcome %>
    <%= f.hidden_field :winner %>
    <%= f.hidden_field :xtimebank %>
    <%= f.hidden_field :otimebank %>
    <%= f.submit style:"display: none;" %>
<% end %>

app/views/matches/index.html.erb
<!-- <%= render 'hidden_create_form' %> -->
<!-- <div class="jumbotron">
  <div class="container">
    <h1>Are You Game!</h1>
    <p>...</p>
  </div>
</div> -->

<div class="container">

  <div class = "well well-sm matches-header">
    <h2>Available Matches</h2>
    <span class="create-game-btn"><%= render 'hidden_create_form' %></span>
  </div>

  <div class="row">
    <% if @availablematches %>
    <% @availablematches.each do |match| %>
      <div class="col-md-2 matches-container">

        <div class="panel panel-default panel-container">

            <div class="panel-body">

              <p class="nameMatch"><%= match.playerx.name %></p>

              <%= button_to("Challenge!", challenge_match_path(match), :method => :patch, class: "btn btn-danger btn-sm challenge-btn" ) %>
            </div>
          </div>
        </div>
      <% end %>
      <% end %>
  </div>

  <div class = "well well-sm matches-header"><h2>Live Matches</h2></div>

  <div class="row">
    <% if @livematches %>
      <% @livematches.each do |match| %>
        <div class="col-md-3 matches-container">
          <div class="panel panel-default panel-container">
            <!-- <div class="panel-heading">Watch Game</div> -->
              <div class="panel-body">
                <p class="nameMatch"><%= match.playerx.name %> VS <%= match.playero.name %></p>
                <div class="btn btn-sm btn-warning watch-game-btn">
                  <%= link_to 'Watch Game', match_path(match), :class => "watch-game-link" %>
                </div>
              </div>

          </div>

        </div>
        <% end %>
      <% end %>
  </div>

</div>

app/views/matches/new.html.erb
<h1>New</h1>

<%= render 'form' %>

app/views/matches/show.html.erb
<div class="game-room-container">

    <div class="game-room row">

        <div class="col-md-8">

            <div class="outcome-message-container jumbotron">
                <h3 class='outcome-message'></h3>
            </div>

            <%= render 'hidden_gameboard_form' %>
            <%= render 'game_board' %>

            <div class="player-dashboard row">

              <div class="col-md-6">
                <div class="player-div player-x-dashboard">

                  <p>White:
                    <%= @match.playerx.name %>
                  </p>
                  <p>Timer:
                    <span class="timebank-X timebank-X-<%= @match.id %>"></span>
                  </p>

                </div>
              </div>


                  <div class="col-md-6">
                    <div class="player-div player-o-dashboard">

                      <p>Black:
                        <span class="player-o-name">
                          <% if @match.playero %>
                          <%= @match.playero.name %>
                          <% else %>
                          Waiting for opponent...
                          <% end %>
                        </span>
                      </p>
                      <p>Timer:
                        <span class="timebank-O timebank-O-<%= @match.id %>"></span>
                      </p>
                    </div>

                  </div>

                </div>

            </div>


        <div class="col-md-4">

            <div class="message-wr">
                <div id="messages" class="messages" data-chat-room-id="<%= @chat_room.id %>">
                    <%= render @chat_room.messages %>
                </div>
            </div>

            <div class="form-group">
                <%= form_for @message, url: '#' do |f| %>
                <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
                <%= f.text_area :body, class: 'form-control' %>
                <% end %>
            </div>

        </div>

    </div>
</div>