config/routes.rb
Rails.application.routes.draw do

  get '/about', to: 'static_pages#about'
  get '/instructions', to: 'static_pages#instructions'
  get '/profile', to: 'users#home'

  devise_for :users, path: '', path_names: {
  sign_in: 'login',
  sign_out: 'logout',
  sign_up: 'register'
}

  resources :matches, except: [:edit, :new] do
    member do
      patch 'challenge', to: 'matches#challenge'
    end
  end

  resources :users
  root "matches#index"

  resources :chat_rooms, only: [:show]

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">

    <small>
        <p><%= link_to image_tag("GA.jpeg", alt: "GA logo", style: "width:15px;height:15px"), 'https://generalassemb.ly/' %>WDI 6 Project 3 - Team Pentago</p>
    </small>

    <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Instructions", instructions_path %></li>

    </ul>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          </div>

          <img class="navbar-brand logo"src="/assets/Slide1.png"/>
          <a class="navbar-brand" href="/matches">PENTA<span class="go">GO</span></a>
            <!-- <%= link_to "Pentago Game", root_path, class: "navbar-brand" %> -->


          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="nav-item navText"><a class="nav-link" href="/matches">Play</a></li>
                <li class="nav-item"><a class="nav-link" href="/instructions">How to Play?</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">

                <% if user_signed_in? %>

                  <li class="nav-item navText"><a class="nav-link" href="/profile"><%= current_user.name %></a></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link" %></li>

                  <% else %>

                  <li><%= link_to "Register", new_user_registration_path, class: "navbar-link" %></li>
                  <li><%= link_to"Login", new_user_session_path, class: "navbar-link" %></li>

                  <% end %>

                </ul>
              </li>
            </ul>

            <!-- <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                <%= link_to current_user.name, profile_path, method: :get, class: "navbar-link" %>

                <%= link_to "Logout", destroy_user_session_path, method:
                :delete, class: "navbar-link" %>

                <% else %>
                <%= link_to "Register", new_user_registration_path, class: "navbar-link" %>
                <%= link_to"Login", new_user_session_path, class: "navbar-link" %>

                <% end %>
            </p> -->


            <!-- <ul class="nav navbar-nav navbar-right">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hi, <%= current_user %><span class="glyphicon glyphicon-circle-arrow-down"></a></span>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul> -->



            <!-- <ul class="nav navbar-nav navbar-right">

                <% if user_signed_in? %>

                  <li class="nav-item navText"><a class="nav-link" href="/profile"><%= current_user%></a></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link" %></li>
                  <% else %>
                  <li><%= link_to "Register", new_user_registration_path, class: "navbar-link" %></li>
                  <li><%= link_to"Login", new_user_session_path, class: "navbar-link" %></li>
                  <% end %>
                </ul>
              </li>
            </ul> -->



            <!-- <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                <%= link_to current_user.name, profile_path, method: :get, class: "navbar-link" %>

                <%= link_to "Logout", destroy_user_session_path, method:
                :delete, class: "navbar-link" %>

                <% else %>
                <%= link_to "Register", new_user_registration_path, class: "navbar-link" %>
                <%= link_to"Login", new_user_session_path, class: "navbar-link" %>

                <% end %>
            </p> -->
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= csrf_meta_tags %>

        <link rel='icon' href='/assets/favicon.ico' type='image/x-icon'/>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <link href="https://fonts.googleapis.com/css?family=Patua+One" rel="stylesheet">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
    <%= render 'layouts/header' %>

        <div class="container">
            <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
            <% end %>
        </div>

        <!-- <div class="container"> -->
            <%= yield %>
        <!-- </div> -->
      <!-- <%= render 'layouts/footer' %> -->
      <!-- Latest compiled and minified JavaScript -->
      <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> -->

    </body>
</html>